# Generated by Django 2.2.4 on 2019-08-19 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcollect', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rdata',
            name='mission_patch_link',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
